export const MarqueeCopies = [
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO",
    "CONSULTA LOS 3 REQUISITOS PARA RENTAR CON NOSOTROS, EN FVTVRA ESTAMOS DE TU LADO"
];